### ISSUE TITLE
docker-compose.yml broken

### ISSUE THREAD

**Issue by kkneutgen** [cracker0dks/whiteboard#42]
Hi,
great project, thank you :)

The current `docker-compose.yml` is broken. It should be something like
```
version: "3.2"
services:
  whiteboard:
    image: rofl256/whiteboard
    ports:
      - "8080:8080"
```
